### ISSUE TITLE
System.Security.Principal.WindowsIdentity error message

### ISSUE THREAD

**Issue by blphu01** [mj1856/SimpleImpersonation#41]
Hello all,

I am new to development and was hoping someone could point me in the right direction.  My code works fine when I run it within VS, however, when I published it as a self-contained package and run the .exe file, I am getting the error message below:

Unhandled Exception: System.IO.FileNotFoundException
   at ConsoleAppNetCore_CopyTable.Program.<>c.<Main>b__0_0()
   at System.Security.Principal.WindowsIdentity.<>c__DisplayClass64_0.<RunImpersonatedInternal>b__0(Object <p0>)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Security.Principal.WindowsIdentity.RunImpersonatedInternal(SafeAccessTokenHandle token, Action action)
   at System.Security.Principal.WindowsIdentity.RunImpersonated(SafeAccessTokenHandle safeAccessTokenHandle, Action action)
   at SimpleImpersonation.Impersonation.RunAsUser(UserCredentials credentials, LogonType logonType, Action action)
   at ConsoleAppNetCore_CopyTable.Program.Main() in C:\Users\bphu\source\repos\ConsoleAppNetCore_CopyTable\ConsoleAppNetCore_CopyTable\Program.cs:line 206

**Comment by mj1856** [comment]
Could you provide a more complete example of the code you're running?  Also, are you running it on Windows, or some other OS?  Is there anything else special about the way you're running the .exe?

**Comment by blphu01** [comment]
Hi Matt, thanks for getting back. Please see below for my code (also excuse me as I am a newbie developer :)

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data.SqlClient;
using SimpleImpersonation;
using System.Data.Common;
using System.Runtime;
using System.Reflection;

//[assembly: AssemblyKeyFileAttribute("BP_sn.pfx")]

namespace ConsoleAppNetCore_CopyTable
{
    using System.Data.SqlClient;
    class Program
    {
        static void Main()
        {
            ///-------------  SimpleImpersonation ------------ ///

            try
            {
                SqlConnectionStringBuilder builder = new SqlConnectionStringBuilder();
                builder.IntegratedSecurity = true;

                var credentials = new UserCredentials("Asia", "myusername", "mypassword");
                Impersonation.RunAsUser(credentials, LogonType.NewCredentials, () =>
                {
                    builder.DataSource = "sqlserver_server1";
                    //builder.UserID = "<your_username>";
                    //builder.Password = "<your_password>";
                    builder.InitialCatalog = "RUBY";
                    using (SqlConnection connection = 
                       new SqlConnection(builder.ConnectionString))
                       {
                    connection.Open();
                        // Now use the open connection.
                        Console.WriteLine("Database = " + connection.Database);
                        Console.WriteLine(connection.State);
                        Console.ReadKey();
                        // Get data from the source table as a SqlDataReader.
                        SqlCommand commandSourceData = new SqlCommand(
                            "SELECT *" +

                            "FROM AIT_General_Extract;", connection);
                        commandSourceData.CommandTimeout = 30000;
                        SqlDataReader reader =
                            commandSourceData.ExecuteReader();
                        // Perform an initial count on the destination table.
                        //SqlCommand commandRowCount = new SqlCommand(
                        //    "SELECT COUNT(*) FROM " +
                        //    "dbo.AIT_General_Extract;",
                        //    connection);
                        //long countStart = System.Convert.ToInt32(
                        //    commandRowCount.ExecuteScalar());
                        //Console.WriteLine("Starting row count = {0}", countStart);

                        SqlConnectionStringBuilder builder2 = new SqlConnectionStringBuilder();
                        builder2.IntegratedSecurity = false;
                        builder2.DataSource = "AH-1052013-001,15001";
                        builder2.UserID = "myusername";
                        builder2.Password = "mypassword";
                        builder2.InitialCatalog = "destination_db";
                        using (SqlConnection connection2 =
                           new SqlConnection(builder2.ConnectionString))
                        {
                            connection2.Open();
                            // Now use the open connection.
                            Console.WriteLine("Database = " + connection2.Database);
                            Console.WriteLine(connection2.State);
                            Console.ReadKey();

                            SqlCommand truncateDestination = new SqlCommand
                            ("truncate table dbo.AIT_General_Extract;", connection2);
                            truncateDestination.CommandTimeout = 30000;
                            truncateDestination.ExecuteNonQuery();

                            using (SqlBulkCopy bulkCopy =
                                  new SqlBulkCopy(connection2))
                            {
                                bulkCopy.DestinationTableName =
                                    "dbo.AIT_General_Extract";
                                bulkCopy.BulkCopyTimeout = 30000;

                                try
                                {
                                    // Write from the source to the destination.
                                    bulkCopy.WriteToServer(reader);
                                    bulkCopy.BatchSize = 1000;
                                    bulkCopy.BulkCopyTimeout = 30000;
                                }
                                catch (Exception ex)
                                {
                                    Console.WriteLine(ex.Message);
                                }
                                finally
                                {
                                    //Close the SqlDataReader.The SqlBulkCopy
                                    //     object is automatically closed at the end
                                    //     of the using block.
                                    reader.Close();
                                    connection2.Close();
                                }
                            }
                        }
                    }

                   

                });
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }


        
        }
    }

}

**Comment by blphu01** [comment]
Hi Matt,

I stripped my code to very bare bone, I created a self-contained .exe to my computer and it works fine, but when I published to a network location or another other place.  I am getting the above error message.  Please see my code below:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data.SqlClient;
using SimpleImpersonation;
using System.Data.Common;
using System.Runtime;
using System.Reflection;


namespace MyTime
{

    using System.Data.SqlClient;
    class Program
    {
        static void Main()
        {
            //try
            //{
                ///-------------  SimpleImpersonation ------------ ///
                var credentials = new UserCredentials("abccomp", "myUsername", "myPassword");
            Impersonation.RunAsUser(credentials, LogonType.NewCredentials, () =>
            {
                Console.WriteLine("Hello.  This is " + credentials);
                Console.ReadKey();
            }
            );
            
        }

    }
}

**Comment by sqladmin-zz** [comment]
LogonType.NewCredentials is only supported with LOGON32_PROVIDER_WINNT50
but in this library method LogonUser is always called with provider type param = 0

here is all available constants for provider type:

public const int LOGON32_PROVIDER_DEFAULT = 0;
public const int LOGON32_PROVIDER_WINNT35 = 1;
public const int LOGON32_PROVIDER_WINNT40 = 2;
public const int LOGON32_PROVIDER_WINNT50 = 3;

you need to check if logontype = LogonType.NewCredentials and then set provider type to 3

**Comment by mj1856** [comment]
@sqladmin-zz - the default behavior should suffice, according to [these docs](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-logonusera#parameters) (read the value/meaning under `dwLogonProvider`)

**Comment by bontibon** [comment]
I was having trouble with an exception being thrown when trying to use `LogonType.NewCredentials` with a local user.

> SimpleImpersonation.ImpersonationException: A logon request contained an invalid logon type value

The problem was that my username was not prefixed with `.\`. I solved it by changing:
```csharp
new SimpleImpersonation.UserCredentials("Username", password);
````
To:
```csharp
new SimpleImpersonation.UserCredentials(@".\Username", password);
```

**Comment by mj1856** [comment]
It sound like this is resolved then.  Thanks.
