### ISSUE TITLE
LogonType.Interactive,LogonType.Unlock Give "System.ComponentModel.Win32Exception: The directory name is invalid" Error

### ISSUE THREAD

**Issue by agoodmiller** [mj1856/SimpleImpersonation#46]
I am trying to use your code to kick off Selenium chromedriver in a Run As environment.

When I use the following code:
```
            var credentials = new UserCredentials(".", "XXXXXXX", "XXXXXXX");
            Impersonation.RunAsUser(credentials, LogonType.Unlock, () =>
            {
                 IWebDriver driver2 = new ChromeDriver("C:\\Selenium\\Drivers\\");
                driver2.Url = "https://google.com";
                driver2.Manage().Window.Maximize();
                driver2.Quit();
            });
```
If i use anything other than "LogonType.Interactive,LogonType.Unlock " it runs the driver and goes through the steps (albeit, not run as the XXXXXXX User.  but as my account).
when i try and run it with LogonType.Interactive or LogonType.Unlock, I get the following error:
Message: 
```
Test method IsmSearchAutoTesting.UnitTest1.openClose threw exception: 
    System.ComponentModel.Win32Exception: The directory name is invalid
  Stack Trace: 
    at Process.StartWithCreateProcess(ProcessStartInfo startInfo)
    at Process.Start()
    at DriverService.Start()
    at DriverServiceCommandExecutor.Execute(Command commandToExecute)
    at RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
    at RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
    at RemoteWebDriver.ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
    at ChromeDriver.ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
    at ChromeDriver.ctor(String chromeDriverDirectory, ChromeOptions options)
    at ChromeDriver.ctor(String chromeDriverDirectory)
    at <>c.<openClose>b__4_0() in UnitTest1.cs line: 157
    at <>c__DisplayClass0_0.<RunAsUser>b__0(SafeAccessTokenHandle _)
    at <>c__DisplayClass4_0.<RunImpersonated>b__0()
    at WindowsIdentity.RunImpersonated(SafeAccessTokenHandle safeAccessTokenHandle, Action action)
    at Impersonation.RunImpersonated(SafeAccessTokenHandle tokenHandle, Action`1 action)
    at Impersonation.RunAsUser(UserCredentials credentials, LogonType logonType, Action action)
    at UnitTest1.openClose() in UnitTest1.cs line: 153
```

Any idea what i could be missing?

**Comment by mj1856** [comment]
Sorry, not sure.  But [here](https://github.com/SeleniumHQ/selenium/blob/9f90d998e990f8464cd989b117686947becfae50/dotnet/src/webdriver/DriverService.cs#L267) is where Selenium is starting the process as shown in your call stack.  And [here](https://stackoverflow.com/questions/990562/win32exception-the-directory-name-is-invalid) is a StackOverflow article talking about how that Win32Exception can be raised when the working directory isn't set.  I wouldn't think that would matter, since you've got an absolute path, but maybe it does (what do I know?) :)

You can try calling [`Directory.SetCurrentDirectory`](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.setcurrentdirectory) yourself, inside the impersonation block to see if that makes a difference.

As far as the logon types - it's simply a pass through to [LogonUser](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-logonuserw), so it's really up to how that function behaves.  The types are iterated in that doc, but indeed some of them are confusing or for older Windows.   I would *guess* that you want `Interactive` for this scenario, but really not sure.
